name: 无知's Blog
description: a powerful jekyll theme
gems: [jekyll-paginate]
url: 'https://nengwuzhi.github.io/' #place url
baseurl:  #place文件夹名称（如果站点位于子文件夹中）
favicon: 'img/favicon.png'
permalink: /:title/
paginate: 10
paginate_path: /page/:num/
tab_dir: all/
author_dir: /author
author_title_prefix: 'Posted by '
media_folder: 
author_default_avatar: /profile-pic.jpg
tumblr: "#"
pinterest: "#"
instagram: "#"
twitter: "#"
facebook: "#"
youtube: "#"
vimeo: "#"
soundcloud: "#"
encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md]

# Navigation buttons in the front page.s
nav:         
    - {title: 作者, description: 关于作者, url: 'https://nengwuzhi.github.io/authors-list'} 
    - {title: 全部, description: 全部文章, url: 'https://nengwuzhi.github.io/all'}
    - {title: 分享, description: dragula, url: 'https://nengwuzhi.github.io/dragula'}

authors:
  
  author1:
    name: 能无知
    site: https://nengwuzhi.github.io/
    avatar: img/avatar1.jpg
    bio: "嗨，我是无知，主题的作者，您当前正在预览的主题。 我希望你喜欢它！"
    email: mailto:author1thunaseer@gmail.com
    twitter: https://twitter.com/nengwuzhi
    instagram: https://www.instagram.com/nengwuzhi/
  
  author2:
    name: 能无为
    site: https://nengwuwei.com/
    avatar: img/avatar2.jpg
    bio: "博主，时尚达人，没有作为！"
    email: mailto:author2chemmengath@gmail.com
    twitter: https://twitter.com/nengwuwei
    instagram: https://www.instagram.com/nengwuwei/
      
# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# prose.io configurations
prose:
  media: "img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          help: "display post at full width or with sidebar"
          options:
            - name: "with sidebar"
              value: "post"
            - name: "full width"
              value: "post_full"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          help: "author id as defined within _data/authors.yml"
          type: "text"
      - name: "featimg"
        field:
          element: "text"
          label: "Featured Image"
          help: "featured image within the img-folder"
          type: "text"
      - name: "type"
        field:
          element: "select"
          label: "Post Type"
          help: "each type has some special feature"
          options:
            - name: "Standard"
              value: "standard"
            - name: "Image"
              value: "image"
            - name: "YouTube"
              value: "youtube"
            - name: "Vimeo"
              value: "vimeo"
      - name: "homedisplay"
        field:
          element: "select"
          label: "Home Display"
          help: "decide whether to display embedded element (for post types: audio, youtube, vimeo) or Featured Image on home page"
          options:
            - name: "Featured Image"
              value: "featimg"
            - name: "Embedded Element"
              value: "iframe"
      - name: "vimeo-embed"
        field:
          element: "text"
          label: "Vimeo Embedding Code"
          help: "Set post type to vimeo in order for this to work"
      - name: "gallery-id"
        field:
          element: "text"
          label: "Gallery ID"
          help: "ID of the gallery defined within _data/galleries.yml - use include in content to use"
      - name: "audio-embed"
        field:
          element: "text"
          label: "Audio Embedding Code"
          help: "Set post type to audio in order for this to work"
      - name: "yt-video-id"
        field:
          element: "text"
          label: "YouTube Video ID"
          help: "Set post type to youtube in order for this to work. Do not set featured image, as the youtube video thumbnail will be used"
          type: "text"

